# Labels for Mentha repository
# These labels help identify issues suitable for new contributors to open source

# Community contribution labels
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "hacktoberfest"
  color: "ff7518"
  description: "Hacktoberfest contribution welcome"
