'use client'

import { useOnboarding } from '@/lib/context/onboarding-context'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Textarea } from '@/components/ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Globe, Building2, Tag, FileText, ImageIcon } from 'lucide-react'
import { useTranslations } from '@/lib/i18n'

const CATEGORIES = [
    { value: 'technology', labelEs: 'Tecnología', labelEn: 'Technology' },
    { value: 'saas', labelEs: 'SaaS', labelEn: 'SaaS' },
    { value: 'ecommerce', labelEs: 'E-commerce', labelEn: 'E-commerce' },
    { value: 'agency', labelEs: 'Agencia', labelEn: 'Agency' },
    { value: 'finance', labelEs: 'Finanzas', labelEn: 'Finance' },
    { value: 'healthcare', labelEs: 'Salud', labelEn: 'Healthcare' },
    { value: 'education', labelEs: 'Educación', labelEn: 'Education' },
    { value: 'real-estate', labelEs: 'Inmobiliaria', labelEn: 'Real Estate' },
    { value: 'manufacturing', labelEs: 'Manufactura', labelEn: 'Manufacturing' },
    { value: 'consulting', labelEs: 'Consultoría', labelEn: 'Consulting' },
    { value: 'facility-management', labelEs: 'Facility Management', labelEn: 'Facility Management' },
    { value: 'logistics', labelEs: 'Logística', labelEn: 'Logistics' },
    { value: 'hospitality', labelEs: 'Hostelería', labelEn: 'Hospitality' },
    { value: 'retail', labelEs: 'Retail', labelEn: 'Retail' },
    { value: 'other', labelEs: 'Otro', labelEn: 'Other' },
]

export default function BrandProfileStep() {
    const { brandProfile, setBrandProfile, nextStep, prevStep } = useOnboarding()
    const { lang } = useTranslations()

    const t = {
        title: lang === 'es' ? 'Perfil de marca' : 'Brand profile',
        subtitle: lang === 'es' ? 'Revisa y edita la información detectada de tu marca' : 'Review and edit your detected brand information',
        logo: lang === 'es' ? 'Logo' : 'Logo',
        logoDetected: lang === 'es' ? 'Logo detectado' : 'Detected logo',
        noLogo: lang === 'es' ? 'Sin logo' : 'No logo',
        companyName: lang === 'es' ? 'Nombre de la empresa' : 'Company name',
        domain: lang === 'es' ? 'Dominio' : 'Domain',
        category: lang === 'es' ? 'Categoría empresarial' : 'Business category',
        selectCategory: lang === 'es' ? 'Selecciona categoría' : 'Select category',
        description: lang === 'es' ? 'Descripción' : 'Description',
        descriptionPlaceholder: lang === 'es' ? 'Describe brevemente tu empresa...' : 'Briefly describe your company...',
        autoGenerated: lang === 'es' ? 'Generada automáticamente, puedes editarla' : 'Auto-generated, you can edit it',
        next: lang === 'es' ? 'Continuar' : 'Continue',
        back: lang === 'es' ? 'Atrás' : 'Back',
        step: lang === 'es' ? 'Paso 3 de 6' : 'Step 3 of 6',
    }

    const handleNext = () => {
        if (brandProfile.name && brandProfile.domain) {
            nextStep()
        }
    }

    return (
        <div className="w-full flex justify-center animate-in fade-in duration-500">
            <Card className="w-full max-w-2xl p-6 md:p-8 space-y-4 shadow-2xl border-white/10 bg-black/40 backdrop-blur-xl">
                {/* Step indicator */}
                <div className="flex items-center justify-between">
                    <span className="text-xs font-medium text-primary bg-primary/10 px-3 py-1 rounded-full">
                        {t.step}
                    </span>
                </div>

                <div className="space-y-2 text-left">
                    <h1 className="text-3xl font-bold tracking-tight text-white">
                        {t.title}
                    </h1>
                    <p className="text-muted-foreground">{t.subtitle}</p>
                </div>

                <div className="space-y-4">
                    {/* Logo preview */}
                    <div className="space-y-1.5">
                        <Label className="text-sm font-medium text-gray-300">{t.logo}</Label>
                        <div className="flex items-center gap-3">
                            <div className="w-12 h-12 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center overflow-hidden">
                                {brandProfile.logo ? (
                                    <img 
                                        src={brandProfile.logo} 
                                        alt="Brand logo" 
                                        className="w-full h-full object-contain p-1.5"
                                    />
                                ) : (
                                    <ImageIcon className="w-6 h-6 text-muted-foreground" />
                                )}
                            </div>
                            <span className="text-sm text-muted-foreground">
                                {brandProfile.logo ? t.logoDetected : t.noLogo}
                            </span>
                        </div>
                    </div>

                    {/* Company name and Domain in same row */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="space-y-1.5">
                            <Label htmlFor="companyName" className="text-sm font-medium text-gray-300">
                                {t.companyName} <span className="text-red-500">*</span>
                            </Label>
                            <div className="relative">
                                <div className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
                                    <Building2 className="w-4 h-4" />
                                </div>
                                <Input
                                    id="companyName"
                                    value={brandProfile.name}
                                    onChange={(e) => setBrandProfile({ ...brandProfile, name: e.target.value })}
                                    placeholder="Acme Inc."
                                    className="h-10 pl-10 bg-white/5 border-white/10 focus:border-primary/50 transition-all"
                                />
                            </div>
                        </div>

                        <div className="space-y-1.5">
                            <Label htmlFor="domain" className="text-sm font-medium text-gray-300">
                                {t.domain} <span className="text-red-500">*</span>
                            </Label>
                            <div className="relative">
                                <div className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
                                    <Globe className="w-4 h-4" />
                                </div>
                                <Input
                                    id="domain"
                                    value={brandProfile.domain}
                                    onChange={(e) => setBrandProfile({ ...brandProfile, domain: e.target.value })}
                                    placeholder="example.com"
                                    className="h-10 pl-10 bg-white/5 border-white/10 focus:border-primary/50 transition-all"
                                />
                            </div>
                        </div>
                    </div>

                    {/* Category */}
                    <div className="space-y-1.5">
                        <Label htmlFor="category" className="text-sm font-medium text-gray-300">
                            {t.category}
                        </Label>
                        <Select
                            value={brandProfile.category}
                            onValueChange={(value) => setBrandProfile({ ...brandProfile, category: value })}
                        >
                            <SelectTrigger className="h-10 bg-white/5 border-white/10 focus:border-primary/50 text-white">
                                <div className="flex items-center gap-2">
                                    <Tag className="w-4 h-4 text-muted-foreground" />
                                    <SelectValue placeholder={t.selectCategory} />
                                </div>
                            </SelectTrigger>
                            <SelectContent>
                                {CATEGORIES.map((cat) => (
                                    <SelectItem key={cat.value} value={cat.value}>
                                        {lang === 'es' ? cat.labelEs : cat.labelEn}
                                    </SelectItem>
                                ))}
                            </SelectContent>
                        </Select>
                    </div>

                    {/* Description */}
                    <div className="space-y-1.5">
                        <Label htmlFor="description" className="text-sm font-medium text-gray-300">
                            {t.description}
                        </Label>
                        <div className="relative">
                            <Textarea
                                id="description"
                                value={brandProfile.description}
                                onChange={(e) => setBrandProfile({ ...brandProfile, description: e.target.value })}
                                placeholder={t.descriptionPlaceholder}
                                rows={3}
                                className="bg-white/5 border-white/10 focus:border-primary/50 transition-all resize-none"
                            />
                        </div>
                        <p className="text-xs text-muted-foreground flex items-center gap-1">
                            <FileText className="w-3 h-3" />
                            {t.autoGenerated}
                        </p>
                    </div>
                </div>

                <div className="flex justify-between pt-2">
                    <Button
                        variant="ghost"
                        onClick={prevStep}
                        className="text-muted-foreground hover:text-white"
                    >
                        {t.back}
                    </Button>
                    <Button
                        onClick={handleNext}
                        disabled={!brandProfile.name || !brandProfile.domain}
                        className="bg-white text-black hover:bg-white/90 px-8 h-10 rounded-md font-medium transition-all disabled:opacity-50"
                    >
                        {t.next}
                    </Button>
                </div>
            </Card>
        </div>
    )
}
